// Text generated from the ladder config: the About page's "How we pick your numbers" pills and
// docs/DATA_RESOLUTION.md (`npm run docs:ladders`; tests/unit/ladder-docs.test.ts fails when stale).

import { LADDERS, LADDER_ORDER, LEVEL_LABELS, type MetricId } from './ladders'
import type { AnyRung } from './resolve'

/** The one-sentence rules shown above the ladders (About page and doc). */
export const RESOLUTION_RULES =
  'Each number compares one series with its own January 2025 value — the same source for the baseline and today, ' +
  'never mixed with another source — taken from the most local step below that has data for your area; ' +
  'if a source publishes nothing there (or is down), we move down one step, and a U.S.-average fallback is always labeled.'

export interface LadderPill {
  rungId: string
  /** Geography, e.g. "City", "PADD region", "HI/AK stand-in". */
  level: string
  /** Source + frequency, e.g. "EIA · weekly". */
  source: string
  /** Plain-English coverage (tooltip / doc). */
  covers: string
}

/** "weekly", "monthly", "twice yearly" (first word, or two for "twice …"; no trailing punctuation). */
const shortFrequency = (f: string) => {
  const w = f.split(/[\s,(]+/).filter(Boolean)
  return (w[0] === 'twice' ? w.slice(0, 2) : w.slice(0, 1)).join(' ')
}

export function ladderPills(metric: MetricId): LadderPill[] {
  return (LADDERS[metric].rungs as AnyRung[]).map((r) => ({
    rungId: r.id,
    level: r.pill ?? LEVEL_LABELS[r.level as keyof typeof LEVEL_LABELS],
    source: `${r.source} · ${shortFrequency(r.frequency)}`,
    covers: r.covers,
  }))
}

const ON_UNAVAILABLE: Record<string, string> = {
  next: 'next step',
  'next-source': 'next step from another source',
  last: 'straight to the U.S. average',
}

const esc = (s: string) => s.replace(/\|/g, '\\|')

/** docs/DATA_RESOLUTION.md, generated. */
export function renderLadderDoc(): string {
  const out: string[] = []
  out.push('<!-- GENERATED by `npm run docs:ladders` from src/lib/resolution/ladders.ts. Do not edit by hand. -->')
  out.push('')
  out.push('# How whatchanged picks each number (source-resolution ladders)')
  out.push('')
  out.push(RESOLUTION_RULES)
  out.push('')
  out.push('Every metric has one **ladder**: an ordered list of rungs, most local first. For a zip, the first rung that')
  out.push('applies and returns data is shown; `/api/data/{zip}` returns every rung\'s outcome as `trace` (✓ used, ✗ unavailable /')
  out.push('no series, – not needed, ⚠ stale), and the site shows it under "Where does this come from?" on each card and graph.')
  out.push('The ladders live in `src/lib/resolution/ladders.ts` (walker: `resolve.ts`); `getGasLookup()` (first applicable live')
  out.push('rung) and `getMetroCpiAreaForCounty()` (first applicable rung) read them, so the snapshot, refresh plan, map and scripts agree.')
  out.push('')
  out.push('When an applicable rung fails at runtime, the rung\'s `onUnavailable` decides what is tried next: the next rung')
  out.push('(default), the next rung from a *different* source (a BLS outage skips the other BLS rungs), or straight to the')
  out.push('U.S. average (the shared, always-warm key). A static source with nothing for a place is "no series here", not an outage.')
  out.push('')
  for (const metric of LADDER_ORDER) {
    const ladder = LADDERS[metric] as { title: string; comparison?: string; noData?: string; rungs: AnyRung[] }
    out.push(`## ${ladder.title} (\`${metric}\`)`)
    out.push('')
    out.push('| # | Rung | Geography | Source | Frequency | Pipeline | If unavailable | Used for |')
    out.push('|---|------|-----------|--------|-----------|----------|----------------|----------|')
    ladder.rungs.forEach((r, i) => {
      out.push(`| ${i + 1} | \`${r.id}\` ${esc(r.label)} | ${esc(r.pill ?? LEVEL_LABELS[r.level as keyof typeof LEVEL_LABELS])} | ` +
        `${esc(r.sourceName)} ([link](${r.homepage})) | ${esc(r.frequency)} | ${r.pipeline} | ` +
        `${i === ladder.rungs.length - 1 ? '—' : ON_UNAVAILABLE[r.onUnavailable ?? 'next']} | ${esc(r.covers)} |`)
    })
    out.push('')
    if (ladder.comparison) out.push(`U.S. comparison: ${ladder.comparison}`)
    if (ladder.noData) out.push(`No rung has data: ${ladder.noData}`)
    const licenses = [...new Set(ladder.rungs.map((r) => `${r.source}: ${r.license}`))]
    out.push(`License / attribution: ${licenses.join('; ')}.`)
    out.push('')
  }
  out.push(HOW_TO_ADD)
  return out.join('\n')
}

/** Kept in sync with the "Resolution ladders" section of CLAUDE.md. */
export const HOW_TO_ADD = `## How to add a rung

1. **Data.** Live source (BLS, EIA, NYSERDA): add a fetcher + cache key and a \`LadderContext\` accessor in
   \`src/lib/resolution/server-context.ts\` (through \`cached-sources.ts\`, so it is budgeted and warmed by the refresh
   plan in \`src/lib/api/refresh.ts\`). Static-pipeline source (Zillow county/metro rent, Alaska DCRA community survey,
   Puerto Rico DACO): ship compact JSON from \`scripts/build-local-data.py\` (+ checks in \`validate-local-data.py\`), read
   it in a small lookup module (\`src/lib/rent.ts\`, \`src/lib/static-gas.ts\`) and expose it as a context accessor.
   \`ladders.ts\` never imports data files, so it stays client-safe (shared facts live in e.g. \`static-gas-meta.ts\`).
2. **Rung.** Insert one \`defineRung({...})\` object at the right position of the metric's \`rungs\` array in
   \`src/lib/resolution/ladders.ts\` (order = most local first): \`id\` (\`{metric}.{slug}\`), plain-English \`label\`,
   \`source\` / \`sourceName\` / \`homepage\` / \`license\`, \`level\`, \`frequency\`, \`pipeline\`, \`covers\`, \`applies(loc)\`
   (true or the reason it doesn't apply), \`target(loc)\`, \`geography(target)\`, \`citationUrl(target)\`, \`resolve(target, ctx)\`
   (used / stale / not-applicable / unavailable / invalid, with \`asOf\`, \`seriesId\` and — when only the data knows it —
   a \`geography\` override) and \`onUnavailable\`. Examples: \`rent.zillow-metro\` (static, between the county rung and
   CPI shelter), \`gas.dcra-community\` (static, keyed by zip, before the HI/AK stand-in), \`gas.daco-pr\` (static, before
   the U.S. average), \`heatingOil.nyserda-region\` (live, before the EIA state rung). A static gas rung returns its own
   \`lookup\` with the value (no cache key); \`selectGasLookup()\` (the refresh plan and map) considers live rungs only.
3. **Snapshot.** If the rung returns a new value shape, map it in \`fetchSnapshot\` (\`src/lib/api/snapshot.ts\`) — e.g. a
   metro rent row becomes \`rent\` with \`level: 'metro'\`. Labels and citations come from the winning rung.
4. **Regenerate + test.** \`npm run docs:ladders\`, add the zip to \`tests/unit/resolution-trace.test.ts\` (trace snapshot)
   and \`tests/unit/golden-zips.test.ts\` if the lookup changes, then \`npm test\`. The About page updates itself.

## How to add a metric (e.g. home heating fuel)

Add a ladder to \`LADDERS\` and \`LADDER_ORDER\` (home heating: \`heatingOil\` = NYSERDA New York region → EIA SHOPP state;
\`propane\` = EIA SHOPP state), its context accessors, a \`TraceMetric\` entry in \`types.ts\`, the snapshot wiring
(\`snapshot.heating\`), the refresh plan, then a graph that passes \`snapshot.trace.{metric}\` to \`EraChart\`'s \`trace\`
prop (\`HeatingChart.tsx\`, tabs only where a source has data). Seasonal sources resolve as \`stale\` off-season with a
plain reason (EIA SHOPP: "Heating-season survey (Oct–Mar) · latest Mar 30, 2026 · next update mid-Oct").
`
